from Tkinter import *
import tkMessageBox
import sqlite3
ph = Tk()

def close():
    ph.destroy()
def info():
    ph.geometry("1000x1000")
    ph.configure(background = "#800020")
    v1= StringVar()
    v2 = StringVar()
    a=PhotoImage(file="contact.gif")
    a=a.subsample(2,2)
    Label(ph,image=a,bg="#E9967A",bd=3).grid(row=1,column=1,columnspan=10)
    Label(ph,text="First Name: ",font = 20,bg = "#800020").grid(row = 2, column = 1)
    e1 = Entry(ph).grid(row = 2, column = 8)
    Label(ph,text = "Middle Name: ",font = 20,bg = "#800020").grid(row = 3,column =1)
    e2 = Entry(ph).grid(row = 3,column = 8)
    Label(ph,text = "Last Name: ",font = 20,bg = "#800020").grid(row = 4,column = 1)
    e3 = Entry(ph).grid(row = 4, column = 8)
    Label(ph,text = "Company Name: ",font = 20,bg = "#800020").grid(row = 5,column = 1)
    e4 = Entry(ph).grid(row = 5,column = 8)
    Label(ph,text = "Address: ",font = 20,bg = "#800020").grid(row = 6,column = 1)
    e5 = Entry(ph).grid(row = 6,column = 8)
    Label(ph,text = "City: ",font = 20,bg = "#800020").grid(row = 7,column = 1)
    e6 = Entry(ph).grid(row = 7,column = 8)
    Label(ph,text = "Pin Code: ",font = 20,bg = "#800020").grid(row = 8,column = 1)
    e7 = Entry(ph).grid(row = 8,column = 8)
    Label(ph,text = "Website URL: ",font = 20,bg = "#800020").grid(row = 9,column = 1)
    e8 = Entry(ph).grid(row = 9,column = 8)
    Label(ph,text = "Date of Birth: ",font = 20,bg = "#800020").grid(row = 10,column = 1)
    e9 = Entry(ph).grid(row = 10,column =8)
    Label(ph,text = "Phone Number ",font = 20,bg = "#800020").grid(row = 11,column = 1)
    e10 = Entry(ph).grid(row = 11,column = 8)
    Label(ph,text = "Select Phone Type: ",fg = "#DC8F25",font = 25,bg = "#800020").grid(row = 12,column = 1)
    Radiobutton(ph,text="Office", variable=v1, value = "Office",font = 15,bg = "#800020").grid(row = 12,column = 7)
    Radiobutton(ph,text="Home",variable=v1,value = "Home",font = 15,bg = "#800020").grid(row = 12,column = 8)
    Radiobutton(ph,text="Mobile",variable = v1, value = "Mobile",font = 15,bg = "#800020").grid(row = 12,column = 9)
    Label(ph,text = "Email id: ",font = 20,bg = "#800020").grid(row =13,column = 1)
    e11 = Entry(ph).grid(row = 13,column = 8)
    Label(ph,text = "Select Email Type: ",fg = "#DC8F25",font = 25,bg = "#800020").grid(row = 14,column = 1)
    Radiobutton(ph,text = "Professional",variable = v2, value = "Professional",font =15,bg = "#800020").grid(row = 14,column = 8)
    Radiobutton(ph,text = "Personal", variable = v2, value = "Personal",font = 15,bg = "#800020").grid(row = 14,column = 9)
    Button(ph,text="Save").grid(row=15,column=2)
    Button(ph,text="Search").grid(row=15,column=7)
    Button(ph,text="Edit").grid(row=15,column=8)
    Button(ph,text="Close",command = close).grid(row=15,column=9)
    
    ph.mainloop()
info()

